export const trainingCopy = {
  en: {
    title: "Your training, on your terms",
    intro:
      "Plan each set. Keep a separate record of what you lifted. No sessions to complete.",
    catalog: "Exercises",
    folders: "Workout folders",
    history: "Lift history",
    admin: "Catalog admin",
    create: "Create exercise",
    shared: "Shared catalog",
    private: "My exercises",
    search: "Search exercises",
    all: "All",
    category: "Category",
    equipment: "Equipment",
    muscle: "Muscle",
    empty: "Nothing here yet. Build your first plan.",
    edit: "Edit",
    archive: "Archive",
    restore: "Unarchive",
    archived: "Archived",
    fallback: "Translation shown in",
    instructions: "Instructions",
    technique: "Technique notes",
    noMedia: "Instructions are available. Exercise media is not cached.",
    name: "Name",
    steps: "Instructions (one step per line)",
    save: "Save on this device",
    saved: "Saved on this device",
    cancel: "Cancel",
    addFolder: "New folder",
    folderName: "Folder name",
    addExercise: "Add exercise",
    addSet: "Add set",
    weight: "Weight",
    reps: "Repetitions",
    remove: "Remove",
    moveUp: "Move up",
    moveDown: "Move down",
    duplicate: "Duplicate",
    delete: "Delete",
    confirm:
      "Delete this record? A recovery draft will be retained on this device.",
    download: "Download for offline",
    downloaded: "Downloaded",
    incomplete: "Metadata saved · some media unavailable",
    clearDownload: "Remove offline download",
    bytes: "Offline storage",
    previous: "Previous lifts",
    record: "Record sets",
    performed: "Performed",
    reference: "Reference only",
    date: "Local date",
    time: "Recorded time",
    notes: "Notes",
    copy: "Copy sets into prescription",
    copied: "Prescription copied explicitly. Lift history is unchanged.",
    tutorial: "My tutorial link",
    tutorialHelp:
      "HTTPS only. Opens online when you choose; no embedded tracking or video download.",
    open: "Open tutorial",
    annotation: "Save my link",
    english: "English",
    arabic: "Arabic",
    error:
      "Check the fields, storage space, and connection. Your existing work remains saved.",
    media: "Optional image or GIF",
    mediaHelp:
      "Private files remain saved locally until uploaded and accepted. Shared catalog media requires licensed provenance through the media API.",
    attach: "Upload and attach",
    online: "Sign in online to upload media.",
    pendingMedia: "Local file saved. Reconnect, then choose Upload and attach.",
    archivedHelp:
      "Archived exercises stay in history and existing prescriptions. They cannot be newly selected.",
    unavailable:
      "Not cached on this device. Connect to load exercises or download a folder.",
    noPrevious: "No previous lifts. Planned sets stay separate from records.",
    visibility: "Visibility",
    selected: "Choose exercise",
    snapshot: "Refresh catalog",
    limit: "Offline exercise media cache is limited to 100 MB.",
    revision: "Version",
    audit: "Catalog changes",
    fields: "Changed fields",
    attention: "Resolve sync conflicts before editing this item.",
    deleteFolder:
      "Delete folder? Lifting history is preserved; recovery draft retained locally.",
    units: "Stored in kilograms; displayed in",
    ordinal: "Set",
    export: "Download recoverable JSON",
    filters: "Exercise filters",
  },
  ar: {
    title: "تدريبك بطريقتك",
    intro: "خطط لكل مجموعة وسجّل ما رفعته بشكل منفصل. لا حاجة لإكمال جلسة.",
    catalog: "التمارين",
    folders: "مجلدات التدريب",
    history: "سجل الأوزان",
    admin: "إدارة الكتالوج",
    create: "إنشاء تمرين",
    shared: "الكتالوج المشترك",
    private: "تماريني",
    search: "ابحث عن تمرين",
    all: "الكل",
    category: "الفئة",
    equipment: "المعدات",
    muscle: "العضلة",
    empty: "لا توجد بيانات بعد. أنشئ خطتك الأولى.",
    edit: "تعديل",
    archive: "أرشفة",
    restore: "إلغاء الأرشفة",
    archived: "مؤرشف",
    fallback: "لغة الترجمة المعروضة",
    instructions: "التعليمات",
    technique: "ملاحظات الأداء",
    noMedia: "التعليمات متاحة. وسائط التمرين غير محفوظة دون اتصال.",
    name: "الاسم",
    steps: "التعليمات (خطوة لكل سطر)",
    save: "حفظ على هذا الجهاز",
    saved: "محفوظ على هذا الجهاز",
    cancel: "إلغاء",
    addFolder: "مجلد جديد",
    folderName: "اسم المجلد",
    addExercise: "إضافة تمرين",
    addSet: "إضافة مجموعة",
    weight: "الوزن",
    reps: "التكرارات",
    remove: "إزالة",
    moveUp: "تحريك لأعلى",
    moveDown: "تحريك لأسفل",
    duplicate: "نسخ",
    delete: "حذف",
    confirm: "حذف هذا السجل؟ ستبقى مسودة للاسترداد على الجهاز.",
    download: "تنزيل للاستخدام دون اتصال",
    downloaded: "تم التنزيل",
    incomplete: "حُفظت البيانات · بعض الوسائط غير متاحة",
    clearDownload: "إزالة التنزيل",
    bytes: "مساحة التخزين دون اتصال",
    previous: "الأوزان السابقة",
    record: "تسجيل المجموعات",
    performed: "تم أداؤها",
    reference: "مرجع فقط",
    date: "التاريخ المحلي",
    time: "وقت التسجيل",
    notes: "ملاحظات",
    copy: "نسخ المجموعات إلى الخطة",
    copied: "تم نسخ الخطة باختيارك. سجل الأوزان لم يتغير.",
    tutorial: "رابط الشرح الخاص بي",
    tutorialHelp:
      "HTTPS فقط. يُفتح باختيارك عبر الإنترنت دون تضمين أو تنزيل فيديو.",
    open: "فتح الشرح",
    annotation: "حفظ رابطي",
    english: "الإنجليزية",
    arabic: "العربية",
    error: "تحقق من الحقول والمساحة والاتصال. بياناتك الحالية ما زالت محفوظة.",
    media: "صورة أو GIF اختياري",
    mediaHelp:
      "تبقى الملفات الخاصة محلياً حتى رفعها وقبولها. وسائط الكتالوج المشترك تتطلب إثبات الترخيص عبر واجهة الوسائط.",
    attach: "رفع وإرفاق",
    online: "سجّل الدخول عبر الإنترنت لرفع الوسائط.",
    pendingMedia: "حُفظ الملف محلياً. اتصل ثم اختر رفع وإرفاق.",
    archivedHelp:
      "تبقى التمارين المؤرشفة في السجل والخطط الحالية ولا يمكن اختيارها من جديد.",
    unavailable:
      "غير محفوظ على هذا الجهاز. اتصل لتحميل التمارين أو تنزيل مجلد.",
    noPrevious: "لا توجد أوزان سابقة. الخطة منفصلة عن سجلات الأداء.",
    visibility: "الظهور",
    selected: "اختر تمريناً",
    snapshot: "تحديث الكتالوج",
    limit: "الحد الأقصى لوسائط التمارين دون اتصال 100 ميجابايت.",
    revision: "الإصدار",
    audit: "تغييرات الكتالوج",
    fields: "الحقول المعدلة",
    attention: "عالج تعارضات المزامنة قبل تعديل هذا العنصر.",
    deleteFolder: "حذف المجلد؟ يبقى سجل الأوزان ومسودة الاسترداد على الجهاز.",
    units: "محفوظ بالكيلوجرام ومعروض بوحدة",
    ordinal: "مجموعة",
    export: "تنزيل JSON للاسترداد",
    filters: "مرشحات التمارين",
  },
};
export const labels: Record<string, [string, string]> = {
  strength: ["Strength", "القوة"],
  cardio: ["Cardio", "كارديو"],
  mobility: ["Mobility", "المرونة"],
  bodyweight: ["Body weight", "وزن الجسم"],
  barbell: ["Barbell", "بار"],
  dumbbell: ["Dumbbell", "دمبل"],
  machine: ["Machine", "جهاز"],
  cable: ["Cable", "كابل"],
  band: ["Band", "حزام مقاومة"],
  kettlebell: ["Kettlebell", "كيتل بيل"],
  other: ["Other", "أخرى"],
  chest: ["Chest", "الصدر"],
  back: ["Back", "الظهر"],
  shoulders: ["Shoulders", "الكتف"],
  biceps: ["Biceps", "العضلة ذات الرأسين"],
  triceps: ["Triceps", "العضلة ثلاثية الرؤوس"],
  quadriceps: ["Quadriceps", "الفخذ الأمامي"],
  hamstrings: ["Hamstrings", "الفخذ الخلفي"],
  glutes: ["Glutes", "الأرداف"],
  calves: ["Calves", "السمانة"],
  core: ["Core", "الجذع"],
  primary: ["Primary", "أساسية"],
  secondary: ["Secondary", "ثانوية"],
};
