# Generated by Django 6.1.1 on 2026-10-05 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('goal', models.CharField(choices=[('cutting', 'Cutting'), ('bulking', 'Bulking')], default='cutting', max_length=7)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='profile_positive_height'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='profile_positive_revision'), models.CheckConstraint(condition=models.Q(('weight_unit__in', ['kg', 'lb'])), name='profile_valid_unit'), models.CheckConstraint(condition=models.Q(('language__in', ['en', 'ar'])), name='profile_valid_language'), models.CheckConstraint(condition=models.Q(('goal__in', ['cutting', 'bulking'])), name='profile_valid_goal')],
            },
        ),
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=10)),
                ('provider_subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='identity_unique_provider_subject'), models.CheckConstraint(condition=models.Q(('provider', 'google')), name='identity_google_provider')],
            },
        ),
    ]
