# Generated by Django 6.1.1 on 2026-10-05 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("effective_date", models.DateField()),
                (
                    "goal",
                    models.CharField(
                        choices=[("cutting", "Cutting"), ("bulking", "Bulking")],
                        max_length=10,
                    ),
                ),
                ("calories_kcal", models.DecimalField(decimal_places=3, max_digits=12)),
                ("protein_g", models.DecimalField(decimal_places=3, max_digits=12)),
                ("carbs_g", models.DecimalField(decimal_places=3, max_digits=12)),
                ("fat_g", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_date", models.DateField()),
                (
                    "goal_snapshot",
                    models.CharField(
                        choices=[("cutting", "Cutting"), ("bulking", "Bulking")],
                        max_length=10,
                    ),
                ),
                (
                    "calorie_target",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "protein_target",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "carb_target",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "fat_target",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nutrition.nutritiontarget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("portion_g", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "calories_kcal",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "brand_source",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("complete", "Complete")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="nutrition.nutritionday",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("portion_g__gt", 0), ("revision__gte", 1)),
                        name="food_entry_positive_portion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "draft"),
                            models.Q(
                                ("status", "complete"),
                                ("calories_kcal__isnull", False),
                                ("carbs_g__isnull", False),
                                ("fat_g__isnull", False),
                                ("protein_g__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="food_entry_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calories_kcal__isnull", True),
                            ("calories_kcal__gte", 0),
                            _connector="OR",
                        ),
                        name="fe_calories_kcal_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("protein_g__isnull", True),
                            ("protein_g__gte", 0),
                            _connector="OR",
                        ),
                        name="fe_protein_g_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("carbs_g__isnull", True),
                            ("carbs_g__gte", 0),
                            _connector="OR",
                        ),
                        name="fe_carbs_g_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fat_g__isnull", True), ("fat_g__gte", 0), _connector="OR"
                        ),
                        name="fe_fat_g_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "effective_date"),
                name="nutrition_target_active_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("goal__in", ["cutting", "bulking"]), ("revision__gte", 1)
                ),
                name="nutrition_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("calories_kcal__gte", 0)),
                name="nt_calories_kcal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("protein_g__gte", 0)), name="nt_protein_g_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("carbs_g__gte", 0)), name="nt_carbs_g_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("fat_g__gte", 0)), name="nt_fat_g_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "local_date"),
                name="nutrition_day_active_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("goal_snapshot__in", ["cutting", "bulking"]), ("revision__gte", 1)
                ),
                name="nutrition_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("calorie_target__isnull", True),
                    ("calorie_target__gte", 0),
                    _connector="OR",
                ),
                name="nd_calorie_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protein_target__isnull", True),
                    ("protein_target__gte", 0),
                    _connector="OR",
                ),
                name="nd_protein_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("carb_target__isnull", True),
                    ("carb_target__gte", 0),
                    _connector="OR",
                ),
                name="nd_carb_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritionday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fat_target__isnull", True),
                    ("fat_target__gte", 0),
                    _connector="OR",
                ),
                name="nd_fat_target_positive",
            ),
        ),
    ]
