export const nutritionCopy = {
  en: {
    recover: "Recovered food drafts",
    restore: "Open as a new draft",
    todayChanged:
      "A new day has started. Choose Start New Day to open today; history stays editable.",
    title: "Nutrition",
    intro:
      "Your food, your numbers. Track the complete portion without estimates.",
    date: "Selected date",
    start: "Start New Day",
    open: "Open selected day",
    empty: "No log for this date. Open it to start recording.",
    targets: "Daily target snapshot",
    schedule: "Target schedule",
    effective: "Effective date",
    goal: "Goal",
    cutting: "Cutting",
    bulking: "Bulking",
    calories_kcal: "Calories (kcal)",
    protein_g: "Protein (g)",
    carbs_g: "Carbohydrates (g)",
    fat_g: "Fat (g)",
    saveTargets: "Save this day’s targets",
    saveSchedule: "Save target schedule",
    scheduleHint:
      "Changes apply to newly opened days. Existing snapshots stay unchanged.",
    name: "Food or meal name",
    portion: "Portion weight (g)",
    portionHint:
      "Nutrition for this portion. Weight never multiplies your nutrients.",
    source: "Brand / source",
    notes: "Notes",
    status: "Entry completeness",
    draft: "Draft (unknown values allowed)",
    complete: "Complete (all four nutrients)",
    save: "Save food",
    edit: "Edit",
    copy: "Copy",
    remove: "Delete",
    cancel: "Cancel editing",
    saved: "Saved on this device. Synchronization is separate.",
    unknown: "Unknown",
    partial: "Partial totals",
    remaining: "remaining",
    over: "over target",
    none: "No entries recorded",
    history: "Week history",
    average: "Average over logged days",
    denominator: "days with at least one entry; missing days excluded",
    move: "Entry date",
    validation:
      "Check your values: positive portion, nonnegative nutrients, and all nutrients for complete entries.",
    future: "Future food dates are outside this release.",
    targetMissing: "Target unknown",
    consumed: "Consumed / target",
    deleteConfirm: "Delete this food entry?",
    confirm: "Confirm deletion",
    back: "Cancel",
    scheduleList: "Saved schedules",
    logged: "Logged days",
    missing: "Not observed",
    snapshotHint:
      "Editing this form explicitly corrects this selected day only.",
  },
  ar: {
    recover: "مسودات الطعام المستردة",
    restore: "فتح كمسودة جديدة",
    todayChanged:
      "بدأ يوم جديد. اختر بدء يوم جديد لفتح اليوم؛ تبقى الأيام السابقة قابلة للتعديل.",
    title: "التغذية",
    intro: "طعامك وأرقامك. سجّل القيم للحصة كاملة دون تقديرات.",
    date: "التاريخ المحدد",
    start: "بدء يوم جديد",
    open: "فتح اليوم المحدد",
    empty: "لا يوجد سجل لهذا التاريخ. افتحه لبدء التسجيل.",
    targets: "أهداف اليوم المحفوظة",
    schedule: "جدول الأهداف",
    effective: "تاريخ السريان",
    goal: "الهدف",
    cutting: "تنشيف",
    bulking: "زيادة الكتلة",
    calories_kcal: "السعرات (كيلوكالوري)",
    protein_g: "البروتين (غ)",
    carbs_g: "الكربوهيدرات (غ)",
    fat_g: "الدهون (غ)",
    saveTargets: "حفظ أهداف هذا اليوم",
    saveSchedule: "حفظ جدول الأهداف",
    scheduleHint:
      "تُطبق التغييرات على الأيام الجديدة فقط. تبقى أهداف الأيام السابقة كما هي.",
    name: "اسم الطعام أو الوجبة",
    portion: "وزن الحصة (غ)",
    portionHint: "القيم الغذائية لهذه الحصة كاملة. الوزن لا يضاعف القيم.",
    source: "العلامة / المصدر",
    notes: "ملاحظات",
    status: "اكتمال الإدخال",
    draft: "مسودة (يمكن ترك القيم غير المعروفة)",
    complete: "مكتمل (القيم الأربع مطلوبة)",
    save: "حفظ الطعام",
    edit: "تعديل",
    copy: "نسخ",
    remove: "حذف",
    cancel: "إلغاء التعديل",
    saved: "تم الحفظ على هذا الجهاز. المزامنة خطوة مستقلة.",
    unknown: "غير معروف",
    partial: "إجماليات جزئية",
    remaining: "متبقي",
    over: "فوق الهدف",
    none: "لا توجد إدخالات مسجلة",
    history: "سجل الأسبوع",
    average: "متوسط الأيام المسجلة",
    denominator: "أيام بها إدخال واحد على الأقل؛ الأيام المفقودة مستبعدة",
    move: "تاريخ الطعام",
    validation:
      "راجع القيم: وزن موجب، وقيم غذائية غير سالبة، والقيم الأربع للإدخال المكتمل.",
    future: "تسجيل الطعام في المستقبل خارج هذا الإصدار.",
    targetMissing: "الهدف غير معروف",
    consumed: "المستهلك / الهدف",
    deleteConfirm: "حذف هذا الإدخال الغذائي؟",
    confirm: "تأكيد الحذف",
    back: "إلغاء",
    scheduleList: "الأهداف المجدولة",
    logged: "الأيام المسجلة",
    missing: "غير مسجل",
    snapshotHint: "تعديل هذا النموذج يصحح أهداف اليوم المحدد فقط.",
  },
};
