export const progressCopy = {
  en: {
    title: "Your progress",
    intro: "Measurements and private photographs, on your terms.",
    weight: "Weight",
    photos: "Private photos",
    date: "Recorded date",
    notes: "Notes",
    save: "Save on this device",
    saved: "Saved on this device. Sync is separate.",
    edit: "Edit",
    delete: "Delete",
    confirm: "Delete this record? Pending work is retained until accepted.",
    cancel: "Cancel",
    empty: "No records yet",
    week: "Assigned week (Monday)",
    capture: "Capture date",
    label: "Optional label",
    file: "Photo (JPEG, PNG or WebP)",
    add: "Stage photo",
    staged:
      "Your photo is safely staged on this device. Acceptance needs a connection.",
    limit: "Four accepted photos per week. Pending uploads remain recoverable.",
    cache: "Cache private photos on this trusted device (up to 50 MB)",
    clear: "Clear cached photos",
    compare: "Compare two weeks",
    left: "First week",
    right: "Second week",
    choose: "Choose photo",
    missing: "Photo unavailable offline. Enable caching while online.",
    zoom: "Zoom original",
    close: "Close",
    reminders: "Reminders",
    reminderIntro:
      "Best effort while this website is open. Browser-closed delivery is not guaranteed.",
    category: "Category",
    food: "Food logging",
    exercise: "Exercise logging",
    photo: "Weekly photo",
    time: "Local time",
    days: "Weekdays (1 Monday–7 Sunday)",
    enabled: "Enable reminder",
    permission: "Notification permission",
    unsupported: "This browser does not support notifications.",
    denied: "Notifications are denied. Other features remain available.",
    generic: "Time for your TrainFuel check-in.",
    unknown: "No weight observations for this week",
    error: "Check the fields or try again. Your local work is retained.",
    history: "Numeric history",
    gaps: "Missing dates are gaps, not zero measurements.",
    replace: "Replace existing photo",
    sync: "Sync now",
  },
  ar: {
    title: "تقدمك",
    intro: "قياسات وصور خاصة حسب اختياراتك.",
    weight: "الوزن",
    photos: "صور خاصة",
    date: "تاريخ القياس",
    notes: "ملاحظات",
    save: "حفظ على هذا الجهاز",
    saved: "تم الحفظ على الجهاز. المزامنة خطوة منفصلة.",
    edit: "تعديل",
    delete: "حذف",
    confirm: "حذف هذا السجل؟ يحتفظ الجهاز بالعمل حتى قبول المزامنة.",
    cancel: "إلغاء",
    empty: "لا توجد سجلات بعد",
    week: "الأسبوع المخصص (الاثنين)",
    capture: "تاريخ التصوير",
    label: "وصف اختياري",
    file: "صورة (JPEG أو PNG أو WebP)",
    add: "حفظ الصورة محلياً",
    staged: "تم حفظ الصورة بأمان على الجهاز. قبولها يحتاج اتصالاً.",
    limit: "أربع صور مقبولة لكل أسبوع. الصور المعلقة قابلة للاستعادة.",
    cache: "حفظ الصور الخاصة على هذا الجهاز الموثوق (حتى ٥٠ ميجابايت)",
    clear: "مسح الصور المحفوظة",
    compare: "مقارنة أسبوعين",
    left: "الأسبوع الأول",
    right: "الأسبوع الثاني",
    choose: "اختيار صورة",
    missing: "الصورة غير متاحة دون اتصال. فعّل الحفظ أثناء الاتصال.",
    zoom: "تكبير الأصل",
    close: "إغلاق",
    reminders: "تذكيرات",
    reminderIntro:
      "تعمل بأفضل جهد أثناء فتح الموقع. الوصول بعد إغلاق المتصفح غير مضمون.",
    category: "الفئة",
    food: "تسجيل الطعام",
    exercise: "تسجيل التمارين",
    photo: "صورة أسبوعية",
    time: "الوقت المحلي",
    days: "أيام الأسبوع (١ الاثنين–٧ الأحد)",
    enabled: "تفعيل التذكير",
    permission: "إذن الإشعارات",
    unsupported: "هذا المتصفح لا يدعم الإشعارات.",
    denied: "الإشعارات مرفوضة. الميزات الأخرى متاحة.",
    generic: "حان وقت متابعة TrainFuel.",
    unknown: "لا توجد قياسات وزن لهذا الأسبوع",
    error: "تحقق من الحقول أو أعد المحاولة. العمل المحلي محفوظ.",
    history: "سجل الأرقام",
    gaps: "التواريخ المفقودة فجوات وليست قياسات صفرية.",
    replace: "استبدال الصورة الحالية",
    sync: "مزامنة الآن",
  },
};
