export const syncCopy = {
  en: {
    title: "Your saved work",
    intro:
      "Changes save on this device first. Sync sends them to your account when you are online.",
    synced: "Synced",
    pending: "Saved on this device · pending sync",
    attention: "Needs your attention",
    syncing: "Syncing…",
    sync: "Sync now",
    paused: "Local access · sign in online to resume sync",
    signin: "Sign in again",
    local: "Your version",
    server: "Account version",
    keep: "Keep my version",
    use: "Use account version",
    deleted: "Deleted on the account. Your work remains in recovered drafts.",
    empty: "All changes have reached your account.",
    drafts: "Recovered drafts",
    logout: "You have unsynced work",
    logoutIntro: "Choose what happens to the changes saved on this device.",
    syncLeave: "Sync, then sign out",
    retain: "Keep on this device and sign out",
    discard: "Discard local work and sign out",
    cancel: "Cancel",
    saved: "Saved on this device",
    offline: "Offline · changes remain saved on this device",
    details: "View sync details",
    export: "Download recovered drafts",
    media: "Staged media",
    retry: "Retry upload",
    remove: "Discard staged file",
    photo: "Cache private photos on this device",
    photoHint: "Off by default. Only enable on a trusted personal device.",
    serverError: "Sync could not finish. Your local work is still saved.",
  },
  ar: {
    title: "عملك المحفوظ",
    intro:
      "تُحفظ التغييرات على هذا الجهاز أولاً، ثم تُزامن مع حسابك عند الاتصال.",
    synced: "تمت المزامنة",
    pending: "محفوظ على هذا الجهاز · بانتظار المزامنة",
    attention: "يحتاج إلى مراجعتك",
    syncing: "جارٍ المزامنة…",
    sync: "مزامنة الآن",
    paused: "وصول محلي · سجّل الدخول عبر الإنترنت لاستئناف المزامنة",
    signin: "تسجيل الدخول مجدداً",
    local: "نسختك",
    server: "نسخة الحساب",
    keep: "الاحتفاظ بنسختي",
    use: "استخدام نسخة الحساب",
    deleted: "حُذف من الحساب. بقي عملك في المسودات المستردة.",
    empty: "وصلت جميع التغييرات إلى حسابك.",
    drafts: "المسودات المستردة",
    logout: "لديك تغييرات لم تُزامن",
    logoutIntro: "اختر ما يحدث للتغييرات المحفوظة على هذا الجهاز.",
    syncLeave: "مزامنة ثم تسجيل الخروج",
    retain: "الاحتفاظ على الجهاز وتسجيل الخروج",
    discard: "حذف العمل المحلي وتسجيل الخروج",
    cancel: "إلغاء",
    saved: "محفوظ على هذا الجهاز",
    offline: "غير متصل · تبقى التغييرات محفوظة على هذا الجهاز",
    details: "عرض تفاصيل المزامنة",
    export: "تنزيل المسودات المستردة",
    media: "الوسائط المحفوظة مؤقتاً",
    retry: "إعادة محاولة الرفع",
    remove: "حذف الملف المحلي",
    photo: "تخزين الصور الخاصة على هذا الجهاز",
    photoHint: "معطّل افتراضياً. فعّله فقط على جهاز شخصي موثوق.",
    serverError: "تعذّر إكمال المزامنة. لا يزال عملك المحلي محفوظاً.",
  },
};
