# Generated by Django 6.1.1 on 2026-10-05 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('export', 'Personal data export'), ('delete', 'Account deletion')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('include_photos', models.BooleanField(default=False)),
                ('result_key', models.CharField(blank=True, max_length=255)),
                ('receipt_digest', models.CharField(max_length=64)),
                ('receipt_expires_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('pending_cleanup', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='privacy_pri_status_600424_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['export', 'delete'])), name='privacy_job_kind'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'ready', 'failed', 'cancelled', 'expired'])), name='privacy_job_status'), models.CheckConstraint(condition=models.Q(('include_photos', True), ('kind', 'delete'), _negated=True), name='privacy_delete_no_photo_export')],
            },
        ),
    ]
