# Generated by Django 6.1.1 on 2026-10-05 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0002_asset_asset_revision_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_translations', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('private', 'Private')], max_length=8)),
                ('category', models.CharField(max_length=40)),
                ('equipment', models.CharField(max_length=40)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('fields', models.JSONField(default=list)),
                ('revision', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tutorial_url', models.URLField(blank=True, max_length=2000)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media_assets.asset')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.JSONField()),
                ('technique_notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='FolderExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('local_date', models.DateField()),
                ('recorded_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('performed', 'Performed'), ('reference', 'Reference')], max_length=9)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('folder_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.folderexercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=9)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='training.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reps', models.PositiveIntegerField()),
                ('folder_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.folderexercise')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reps', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.exerciserecord')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folderexercise',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='training.workoutfolder'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('visibility', 'shared')), models.Q(('owner__isnull', False), ('visibility', 'private')), _connector='OR'), name='training_exercise_visibility_owner'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'exercise'), name='training_annotation_active_pair'),
        ),
        migrations.AddConstraint(
            model_name='exercisemedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset',), name='training_media_active_asset'),
        ),
        migrations.AddConstraint(
            model_name='exercisemedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('exercise', 'position'), name='training_media_active_position'),
        ),
        migrations.AddConstraint(
            model_name='exercisemedia',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='training_media_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='exercisetext',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('exercise', 'language'), name='training_text_active_language'),
        ),
        migrations.AddIndex(
            model_name='exerciserecord',
            index=models.Index(fields=['user', 'exercise', 'local_date'], name='training_ex_user_id_784f32_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciserecord',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['performed', 'reference'])), name='training_record_kind'),
        ),
        migrations.AddConstraint(
            model_name='exercisemuscle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('exercise', 'muscle'), name='training_muscle_active_pair'),
        ),
        migrations.AddConstraint(
            model_name='exercisemuscle',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'secondary'])), name='training_muscle_role'),
        ),
        migrations.AddConstraint(
            model_name='plannedset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('folder_exercise', 'position'), name='training_planned_position'),
        ),
        migrations.AddConstraint(
            model_name='plannedset',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0), ('reps__gt', 0), ('weight_kg__gte', 0)), name='training_planned_values'),
        ),
        migrations.AddConstraint(
            model_name='recordedset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('record', 'position'), name='training_recorded_position'),
        ),
        migrations.AddConstraint(
            model_name='recordedset',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0), ('reps__gt', 0), ('weight_kg__gte', 0)), name='training_recorded_values'),
        ),
        migrations.AddConstraint(
            model_name='workoutfolder',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='training_folder_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='folderexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('folder', 'position'), name='training_folder_entry_position'),
        ),
        migrations.AddConstraint(
            model_name='folderexercise',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='training_entry_position_positive'),
        ),
    ]
