# Generated by Django 6.1.1 on 2026-10-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_profiles'),
        ('training', '0002_muscles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderOrder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
