# Generated by Django 6.1.1 on 2026-10-05 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('retention_floor', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('web', 'web'), ('android', 'android'), ('ios', 'ios')], default='web', max_length=10)),
                ('last_ack_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=10)),
                ('base_revision', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('conflict', 'conflict'), ('rejected', 'rejected')], max_length=10)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sync.device')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('entity_revision', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('upsert', 'upsert'), ('delete', 'delete')], max_length=10)),
                ('scope', models.CharField(choices=[('owner', 'owner'), ('catalog', 'catalog')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'sequence'], name='sync_change_owner_i_12d966_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('scope', 'owner')), models.Q(('owner__isnull', True), ('scope', 'catalog')), _connector='OR'), name='change_scope_owner')],
            },
        ),
    ]
