# Generated by Django 6.1.1 on 2026-10-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changerecord',
            constraint=models.CheckConstraint(condition=models.Q(('entity_revision__gte', 1)), name='change_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='changerecord',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['upsert', 'delete'])), name='change_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('platform__in', ['web', 'android', 'ios'])), name='sync_device_platform'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'delete'])), name='sync_operation_action'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['accepted', 'conflict', 'rejected'])), name='sync_operation_status'),
        ),
    ]
