# Generated by Django 6.1.1 on 2026-10-05 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('visibility', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=10)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('deleted', 'deleted')], default='processing', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media_assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('exercise', 'exercise'), ('progress', 'progress')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('finalized', 'finalized'), ('failed', 'failed')], default='pending', max_length=10)),
                ('staging_key', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media_assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('visibility', 'private')), models.Q(('owner__isnull', True), ('visibility', 'public')), _connector='OR'), name='asset_visibility_owner'),
        ),
        migrations.AddConstraint(
            model_name='attachmentclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset',), name='asset_one_active_attachment'),
        ),
    ]
