# Generated by Django 6.1.1 on 2026-10-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='asset_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['processing', 'ready', 'deleted'])), name='asset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), ('byte_size__gt', 0), _connector='OR'), name='ready_asset_has_bytes'),
        ),
        migrations.AddConstraint(
            model_name='upload',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['exercise', 'progress'])), name='upload_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='upload',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'finalized', 'failed'])), name='upload_status_valid'),
        ),
    ]
